apt:
  sources:
  - deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe
    multiverse
  - deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe
    multiverse
  - deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe
    multiverse
  packages:
  - libdconf1:amd64=0.24.0-2
  - libcapnp-0.5.3:amd64=0.5.3-2ubuntu1.1
  - libstdc++6:amd64=5.4.0-6ubuntu1~16.04.12
  - libselinux1:amd64=2.4-3build2
  - libpcre3:amd64=2:8.38-3.1
  - libkrb5support0:amd64=1.13.2+dfsg-5ubuntu2.2
  - libprotobuf-lite9v5:amd64=2.6.1-1.3
  - xkb-data:all=2.16-1ubuntu1
  - libatspi2.0-0:amd64=2.18.3-4ubuntu1
  - libxkbcommon0:amd64=0.5.0-1ubuntu2.1
  - libpng12-0:amd64=1.2.54-1ubuntu1.1
  - libatk-bridge2.0-0:amd64=2.18.1-2ubuntu1
  - libatk1.0-data:all=2.18.0-1
  - libxi6:amd64=2:1.7.6-1
  - libgdk-pixbuf2.0-common:all=2.32.2-1ubuntu1.6
  - libcups2:amd64=2.1.3-4ubuntu0.11
  - libavahi-client3:amd64=0.6.32~rc+dfsg-1ubuntu2.3
  - libgssapi-krb5-2:amd64=1.13.2+dfsg-5ubuntu2.2
  - gcc-6-base:amd64=6.0.1-0ubuntu1
  - libgraphite2-3:amd64=1.3.10-0ubuntu0.16.04.1
  - libgtk-3-0:amd64=3.18.9-1ubuntu3.3
  - fontconfig-config:all=2.11.94-0ubuntu1.1
  - libdbus-1-3:amd64=1.10.6-1ubuntu3.6
  - libboost-system1.58.0:amd64=1.58.0+dfsg-5ubuntu3.1
  - libatk1.0-0:amd64=2.18.0-1
  - libgcc1:amd64=1:6.0.1-0ubuntu1
  - libcairo2:amd64=1.14.6-1
  - libcairo-gobject2:amd64=1.14.6-1
  - libgtk-3-common:all=3.18.9-1ubuntu3.3
  - libffi6:amd64=3.2.1-4
  - libcomerr2:amd64=1.42.13-1ubuntu1.2
  - libxcomposite1:amd64=1:0.4.4-1
  - libxext6:amd64=2:1.3.3-1
  - libexpat1:amd64=2.1.0-7ubuntu0.16.04.5
  - libsqlite3-0:amd64=3.11.0-1ubuntu1.5
  - libc6:amd64=2.23-0ubuntu11.3
  - libkrb5-3:amd64=1.13.2+dfsg-5ubuntu2.2
  - libmircommon7:amd64=0.26.3+16.04.20170605-0ubuntu1.1
  - libthai-data:all=0.1.24-2
  - libdatrie1:amd64=0.2.10-2
  - libpango-1.0-0:amd64=1.38.1-1
  - libtiff5:amd64=4.0.6-1ubuntu0.8
  - libepoxy0:amd64=1.3.1-1ubuntu0.16.04.2
  - libp11-kit0:amd64=0.23.2-5~ubuntu16.04.2
  - liblzma5:amd64=5.1.1alpha+20120614-2ubuntu2
  - libfontconfig1:amd64=2.11.94-0ubuntu1.1
  - libsoup-gnome2.4-1:amd64=2.52.2-1ubuntu0.3
  - libjpeg8:amd64=8c-2ubuntu8
  - libhogweed4:amd64=3.2-1ubuntu0.16.04.2
  - gcc-5-base:amd64=5.4.0-6ubuntu1~16.04.12
  - libjbig0:amd64=2.1-3.1
  - libavahi-common3:amd64=0.6.32~rc+dfsg-1ubuntu2.3
  - libxrender1:amd64=1:0.9.9-0ubuntu1
  - libproxy1v5:amd64=0.4.11-5ubuntu1.2
  - libjson-glib-1.0-0:amd64=1.1.2-0ubuntu1
  - libxcursor1:amd64=1:1.1.14-1ubuntu0.16.04.2
  - libgcrypt20:amd64=1.6.5-2ubuntu0.6
  - libk5crypto3:amd64=1.13.2+dfsg-5ubuntu2.2
  - libboost-filesystem1.58.0:amd64=1.58.0+dfsg-5ubuntu3.1
  - libnettle6:amd64=3.2-1ubuntu0.16.04.2
  - libxrandr2:amd64=2:1.5.0-1
  - libfreetype6:amd64=2.6.1-0.1ubuntu2.5
  - libmirclient9:amd64=0.26.3+16.04.20170605-0ubuntu1.1
  - libgnutls30:amd64=3.4.10-4ubuntu1.9
  - glib-networking-common:all=2.48.2-1~ubuntu16.04.2
  - libjson-glib-1.0-common:all=1.1.2-0ubuntu1
  - dconf-gsettings-backend:amd64=0.24.0-2
  - libwayland-cursor0:amd64=1.12.0-1~ubuntu16.04.3
  - libsystemd0:amd64=229-4ubuntu21.31
  - libicu55:amd64=55.1-7ubuntu0.5
  - libxinerama1:amd64=2:1.1.3-1
  - librest-0.7-0:amd64=0.7.93-1
  - libjpeg-turbo8:amd64=1.4.2-0ubuntu3.4
  - fonts-dejavu-core:all=2.35-1
  - libcolord2:amd64=1.2.12-1ubuntu1
  - libharfbuzz0b:amd64=1.0.1-1ubuntu0.1
  - dconf-service:amd64=0.24.0-2
  - libkeyutils1:amd64=1.5.9-8ubuntu1
  - libmircore1:amd64=0.26.3+16.04.20170605-0ubuntu1.1
  - libsoup2.4-1:amd64=2.52.2-1ubuntu0.3
  - libxfixes3:amd64=1:5.0.1-2
  - glib-networking-services:amd64=2.48.2-1~ubuntu16.04.2
  - libgdk-pixbuf2.0-0:amd64=2.32.2-1ubuntu1.6
  - libthai0:amd64=0.1.24-2
  - zlib1g:amd64=1:1.2.8.dfsg-2ubuntu4.3
  - glib-networking:amd64=2.48.2-1~ubuntu16.04.2
  - gsettings-desktop-schemas:all=3.18.1-1ubuntu1
  - libtasn1-6:amd64=4.7-3ubuntu0.16.04.3
  - libwayland-client0:amd64=1.12.0-1~ubuntu16.04.3
  - libpangocairo-1.0-0:amd64=1.38.1-1
  - libxdamage1:amd64=1:1.1.4-2
  - libxml2:amd64=2.9.3+dfsg1-1ubuntu0.7
  - libgmp10:amd64=2:6.1.0+dfsg-2
  - libudev1:amd64=229-4ubuntu21.31
  - libpixman-1-0:amd64=0.33.6-1
  - libmirprotobuf3:amd64=0.26.3+16.04.20170605-0ubuntu1.1
  - libavahi-common-data:amd64=0.6.32~rc+dfsg-1ubuntu2.3
  - libwayland-egl1-mesa:amd64=18.0.5-0ubuntu0~16.04.1
  - libpangoft2-1.0-0:amd64=1.38.1-1
  - liblcms2-2:amd64=2.6-3ubuntu2.1
  - libidn11:amd64=1.32-3ubuntu1.2
  - libgpg-error0:amd64=1.21-2ubuntu1
